{{- if .Values.spinnakerOperator.customConfiguration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.spinnakerOperator.customConfiguration.name }}"
{{- with .Values.spinnakerOperator.customConfiguration.data }}
data:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}