{{- if and .Values.spinnakerOperator.enabled .Values.spinnakerOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spinnaker-operator.operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "spinnaker-operator.name" . }}
{{- include "spinnaker-operator.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.spinnakerOperator.imagePullSecrets | indent 2 }}
{{ end }}