# Default values for spinnaker-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of spinnaker-operator for `app:` labels
##
nameOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

spinnakerOperator:
  enabled: true

  rbac:
    create: true

  serviceAccount:
    create: true
    name: "spinnaker-operator"

  imagePullSecrets: []

  customConfiguration:
    enabled: false
    name: halyard-custom-config
    data:
      halyard-local.yml: |
        secrets:
          vault:
            enabled: false

  operator:
    image:
      repository: index.docker.io/armory/armory-operator
      tag: 1.2.0
      pullPolicy: IfNotPresent

    resources: {}

    volumeMounts: []

  halyard:
    image:
      repository: index.docker.io/armory/halyard-armory
      tag: operator-97b4194c9fce0616a995c2addaa0aad75a6e4627
      pullPolicy: IfNotPresent

    resources: {}

    volumeMounts: []
  ## Labels to add to the operator pod
  ##
  podLabels: {}

  ## Annotations to add to the operator pod
  ##
  podAnnotations: {}

  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Tolerations for use with node taints
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"

  ## Assign custom affinity rules to the armory operator
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  affinity: {}
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: kubernetes.io/e2e-az-name
    #         operator: In
    #         values:
    #         - e2e-az1
    #         - e2e-az2

  securityContext: {}
    # runAsNonRoot: true
    # runAsUser: 65534

  commonLabels: {}

  ## Assign custom volumes rules to the armory operator
  ## ref: https://docs.armory.io/spinnaker/operator/#custom-halyard-configuration
  volumes: []

spinnakerService:

  enabled: false

  apiVersion: spinnaker.armory.io/v1alpha2

  metadata:
    name: spinnaker
    namespace: default

  spinnakerConfig:
    config:
      version: 2.17.1
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: <change-me>
          rootFolder: front50
  expose:
    type: service
    service:
      type: LoadBalancer

  validation: {}
  kustomize: {}
