apiVersion: v1
kind: ConfigMap
metadata:
  name: halyard-config-map
data:
  config: |
    halyard:
      halconfig:
        directory: /Users/spinnaker/.hal
    spinnaker:
      config:
        input:
          bucket: halconfig
          region: us-west-2
    secrets:
      vault:
        enabled: false
        url: https://vault.url
        path: example
        role: example
        authMethod: KUBERNETES